name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srsran:$(date +%s)
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
     
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        tags: srsran:latest
        outputs: type=oci,dest=/tmp/myimage.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myimage
        path: /tmp/myimage.tar
